### ISSUE TITLE
Incorrect canvas boundary checking for single pixel

### ISSUE THREAD

**Issue by MrCrackerplays** [Obult/canvas.edu#10]
It's currently possible for single pixel putting to put pixels exactly 1 coordinate beyond the bounds of the canvas ([x=200 or y=200](https://github.com/Obult/canvas.edu/blob/4cdf2b252a0b48205739838db0ec2a6d87b5b3e6/backend/volume/src/canvas/canvas.controller.ts#L77) them being wrong due to the canvas being 0-199, 0-199)

**Comment by Obult** [comment]
Good catch!
I am aware of the issue but will leave it in till we switch over to a config for the canvas size

**Comment by Obult** [comment]
[Fixed] but as i said before needs to be done some work on still when adding a config file in the future
also added the bounds checking on multiple endpoint so it cannot be used to break the server.
Fixd in commit 3c2a2535125327968f027fc3b28516e40dbffa4e
